TRUNCATE TABLE Meritve_Feb_12
TRUNCATE TABLE Meritve_Jan_12

DELETE FROM [dbo].[Izravnava] WHERE DATEPART(MONTH,interval) = 2 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[Regulacija] WHERE DATEPART(MONTH,interval) = 2 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[TrzniPlan] WHERE DATEPART(MONTH,interval) = 2 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[Izpadi] WHERE DATEPART(MONTH,interval) = 2 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[Izjeme] WHERE DATEPART(MONTH,interval) = 2 AND DATEPART(YEAR,Interval)=2012

DELETE FROM [dbo].[Izravnava] WHERE DATEPART(MONTH,interval) = 1 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[Regulacija] WHERE DATEPART(MONTH,interval) = 1 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[TrzniPlan] WHERE DATEPART(MONTH,interval) = 1 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[Izpadi] WHERE DATEPART(MONTH,interval) = 1 AND DATEPART(YEAR,Interval)=2012
DELETE FROM [dbo].[Izjeme] WHERE DATEPART(MONTH,interval) = 1 AND DATEPART(YEAR,Interval)=2012
